const DEFAULT_CONFIG_COLOR = "#000000";
const DEFAULT_CONFIG_SIZE = 16;
const DEFAULT_CONFIG_MESSAGE = "Default message";

module.exports = {
  DEFAULT_CONFIG_COLOR,
  DEFAULT_CONFIG_SIZE,
  DEFAULT_CONFIG_MESSAGE,
};
